#!/usr/bin/python

""" Module for registration of the app """

import os
import sys

#from run import app as application
from app import C_APP as application

sys.path.insert(0, os.path.dirname(__file__) or '.')
PY_DIR = os.path.join(os.environ['OPENSHIFT_HOMEDIR'], "python")
C_VIRTENV = PY_DIR + '/virtenv/'
PY_CACHE = os.path.join(C_VIRTENV
                        , 'lib'
                        , os.environ['OPENSHIFT_PYTHON_VERSION']
                        , 'site-packages')
os.environ['PYTHON_EGG_CACHE'] = os.path.join(PY_CACHE)
C_ACT_VIRENV = os.path.join(C_VIRTENV, 'bin/activate_this.py')

#virtenv = os.environ['APPDIR'] + '/virtenv/'
#os.environ['PYTHON_EGG_CACHE'] = os.path.join(virtenv, 'lib/python2.7/site-packages')
#virtualenv = os.path.join(virtenv, 'bin/activate_this.py')

try:
    execfile(open(C_ACT_VIRENV).read(), dict(__file__=C_ACT_VIRENV))
except IOError:
    pass

